"""Add refund_status to orders

Revision ID: 0fc65e8e4437
Revises: 5b74173e4fba
Create Date: 2026-08-13 21:52:15.720884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc65e8e4437'
down_revision: Union[str, Sequence[str], None] = '5b74173e4fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('refund_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'refund_status')
    # ### end Alembic commands ###
