"""Add order tracking fields

Revision ID: 267f79d51044
Revises: 858db6740a45
Create Date: 2026-08-13 20:58:55.980316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267f79d51044'
down_revision: Union[str, Sequence[str], None] = '858db6740a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('courier_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimated_delivery')
    op.drop_column('orders', 'courier_name')
    op.drop_column('orders', 'tracking_number')
    # ### end Alembic commands ###
