"""Add transaction_id to Order

Revision ID: 858db6740a45
Revises: ba0941146d06
Create Date: 2026-08-13 12:40:42.170151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858db6740a45'
down_revision: Union[str, Sequence[str], None] = 'ba0941146d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('transaction_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'transaction_id')
    # ### end Alembic commands ###
